// flow-typed signature: beace27bafff460ba98df7630e93047b
// flow-typed version: <<STUB>>/enzyme-react-intl_v^2.0.1/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'enzyme-react-intl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'enzyme-react-intl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'enzyme-react-intl/lib/enzyme-react-intl' {
  declare module.exports: any;
}

// Filename aliases
declare module 'enzyme-react-intl/lib/enzyme-react-intl.js' {
  declare module.exports: $Exports<'enzyme-react-intl/lib/enzyme-react-intl'>;
}
